import { Inter } from "next/font/google";
import "./globals.css";
import './styles.css'
import { SidebarProvider } from "@/contexts/SidebarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-white  no-scrollbar relative qs-font'}>
        <SidebarProvider>
          {children}

        </SidebarProvider>
      </body>
    </html>
  );
}
